### ISSUE TITLE
train combine mode error

### ISSUE THREAD

**Issue by yja1** [huanghoujing/beyond-part-models#10]
python script/experiment/train_pcb.py \
-d '(0,)' \
--only_test false \
--dataset combined \
--trainset_part trainval \
--exp_dir /data/exp_directory \
--steps_per_log 20 \
--epochs_per_val 2

the error in bpm/dataset/__init__.py 
elif name == 'combined':
assert part in ['trainval'], "Only trainval part of the combined dataset is available now."

**Comment by huanghoujing** [comment]
Thank you for your attention!

This is my mistake, more explanation is [here](https://github.com/huanghoujing/person-reid-triplet-loss-baseline/issues/4).

**Comment by yja1** [comment]
I have train a combined model. so if I test the model on 3 datasets respectively should I change something?
I run:
python script/experiment/train_pcb.py 
-d '(0,)' 
--only_test true
--dataset duke 
--exp_dir /data/exp_directory 

error:
While copying the parameter named fc_list.0.weight, whose dimensions in the model are torch.Size([702, 256]) and whose dimensions in the checkpoint are torch.Size([2220, 256]), ...

**Comment by huanghoujing** [comment]
Here changing your parameter `--dataset duke` to `--dataset combined` should solve the problem. When `combined` dataset is used, the test sets are three sub test sets, which I hard coded [here](https://github.com/huanghoujing/beyond-part-models/blob/f4697a689c61258f6ccfc2eccec2ec05f0130f28/script/experiment/train_pcb.py#L308-L312). The code would test on three sub test sets.

**Comment by yja1** [comment]
you mean train combined model test on combined dataset. 

but your "market1501_cuhk03_duke/partitions.pkl"  only have dict_keys(['trainval_im_names', 'trainval_ids2labels'])

run at the line you point out "test_sets.append(create_dataset(**cfg.test_set_kwargs))"
has error:
`im_names = partitions['{}_im_names'.format(part)]
KeyError: 'test_im_names'`
there is no key which name 'test'.

I try run combine_trainval_sets.py to generate combined dataset pkl also has this error.
