### ISSUE TITLE
你好 我想问一下，我怎样才能用你的模型测试我的数据集呢？

### ISSUE THREAD

**Issue by ds-gong** [huanghoujing/beyond-part-models#19]
我想用你训练好的模型（或者我训练自己的数据集模型），测试我的数据集，并且得到score 和 top5，top10，该怎么做呢？谢谢~

**Comment by huanghoujing** [comment]
你好，只需要把你的数据集处理成这里相应的格式即可。参见我之前[一个回复](https://github.com/huanghoujing/person-reid-triplet-loss-baseline/issues/9)。
