### ISSUE TITLE
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

### ISSUE THREAD

**Issue by gosuncn180503** [huanghoujing/beyond-part-models#22]
我这边运行代码出现下面的问题，请问您是否有遇到过？
`----------------------------------------
NO. Images: 31969
NO. IDs: 751
NO. Query Images: 3368
NO. Gallery Images: 15913
NO. Multi-query Images: 12688
----------------------------------------
./bpm/model/PCBModel.py:38: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(fc.weight, std=0.001)
./bpm/model/PCBModel.py:39: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(fc.bias, 0)
Traceback (most recent call last):
  File "script/experiment/train_pcb.py", line 499, in <module>
    main()
  File "script/experiment/train_pcb.py", line 439, in main
    torch.cat([criterion(logits, labels_var) for logits in logits_list]))
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated
*** Error in `python': realloc(): invalid pointer: 0x00007fa5309148a0 ***
`

**Comment by huanghoujing** [comment]
你好，`zero-dimensional tensor (at position 0) cannot be concatenated`这个问题我估计是pytorch 0.4跑出来的，你用pytorch 0.3应该没问题。

**Comment by gosuncn180503** [comment]
你好，我试了一下，改成了pytorch0.3，确实是可以了，非常感谢！

**Comment by huanghoujing** [comment]
不客气哈
