### ISSUE TITLE
Shared 1x1 Conv vs. Independent 1x1 Conv

### ISSUE THREAD

**Issue by yyvettey** [huanghoujing/beyond-part-models#28]
Could you please explain the differences between these two in details? Would appreciated it if you could point out in the code. Many thanks!

**Comment by huanghoujing** [comment]
Hi, `(Shared 1x1 Conv)` means there is only one 1x1 Conv layer after pooling, shared between all parts/stripes (There are 6 parts, as an example). `Independent 1x1 Conv` means each part is processed by its 1x1 Conv layer, meaning different parts are processed by different model weights. The `(Shared 1x1 Conv)` implementation can only be found in early versions of code, not in current commit.

**Comment by abhishekaich27** [comment]
Hi @huanghoujing ! So now the implementation is for each stripe having it's own classifier as described in Figure 2 of the base paper?

**Comment by huanghoujing** [comment]
@abhishekaich27 Yes, you are right.
