### ISSUE TITLE
Testing results on CUHK03

### ISSUE THREAD

**Issue by iodicesara** [huanghoujing/beyond-part-models#6]
Hi, I tried to train the model on CUHK03 and repeat the experiment, but results I got are lower compared to those reported on the paper, i.e. 
Single Query:                 [mAP: 41.74%], [cmc1: 46.36%], [cmc5: 67.43%], [cmc10: 75.71%]
Re-ranked Single Query:       [mAP: 58.11%], [cmc1: 56.71%], [cmc5: 69.71%], [cmc10: 77.00%]

Do you know any reasons of that?
Thanks.

**Comment by huanghoujing** [comment]
Well, maybe it's because of some little but non-trivial differences between my implementation and the author's, which are not detailed in the paper. I have no idea also : )

**Comment by huanghoujing** [comment]
The PCB baseline on CUHK03 is now quite normal after using independent 1x1 conv for each part. On CUHK03, the Rank-1 accuracy and mAP are about 2 and 0.5 points lower than the paper, respectively.
