### ISSUE TITLE
有关README

### ISSUE THREAD

**Issue by luyang-NWPU** [huanghoujing/beyond-part-models#7]
在README里提到：
|                   | Rank-1 (%) | mAP (%) | R.R. Rank-1 (%) | R.R. mAP (%) |
| Market1501 (Paper)| 92.40 | 77.30 | -     | -     |

可是我看论文中说的是：“In this paper, we report **mAP = 81.6%**, 69.2%, 57.5%
and **Rank-1 = 93.8%**, 83.3% and 63.7% for Market-
1501, Duke and CUHK03, respectively, setting new state
of the art on the three datasets. All the results are achieved
under the single-query mode without re-ranking. Re-
ranking methods will further boost the performance espe-
cially mAP. For example, when “PCB+RPP” is combined
with the method in [44], mAP and Rank-1 accuracy on
Market-1501 increases to 91.9% and 95.1%, respectively.”

为什么您提到的论文数据不一致呢？是我看错了么...

**Comment by ZongweiZhou1** [comment]
代码中没有实现RPP部分，你说的是PCB+RPP的结果，看Table1
