### ISSUE TITLE
test error in market 1501

### ISSUE THREAD

**Issue by chegnyanjun** [huanghoujing/beyond-part-models#9]
您好，我下载了您训练好的market1501数据集的模型文件，利用它测试时效果不好，我不知道是什么问题，你知道原因吗，谢谢啦！
![2018-03-23 16-24-08](https://user-images.githubusercontent.com/25890292/37819649-2992d038-2eb9-11e8-9dfd-41f2f360bd8b.png)

**Comment by huanghoujing** [comment]
你好，多谢关注！这里提供的训练模型，我测试的时候没有遇到这样的问题；但是我在其它实验中训练崩溃时测出来有类似这样的分数，mAP接近50，rank-1超级低。你这个问题我无法解决。。。

**Comment by chegnyanjun** [comment]
我发现这样的错误应该是版本不一致导致的，把 pytorch从0.3改为0.3.1后，测试结果完美，谢谢啦！

**Comment by huanghoujing** [comment]
好神奇！我提交这个代码的时候貌似还没出pytorch0.3.1
